### ISSUE TITLE
build faild

### ISSUE THREAD

**Issue by Neo110** [jbolda/redacted#5]
[ERROR rust_analyzer::main_loop] FetchBuildDataError:
error: failed to run custom build command for `redacted v0.0.0 (/Users/zhengbin/Downloads/redacted-main/src-tauri)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/Users/zhengbin/Downloads/redacted-main/src-tauri/target/debug/build/redacted-54a1a0756129d305/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=TAURI_CONFIG
  cargo:rerun-if-changed=tauri.conf.json
  cargo:rustc-cfg=desktop

        The `tauri` dependency features on the `Cargo.toml` file does not match the allowlist defined under `tauri.conf.json`.
        Please run `tauri dev` or `tauri build` or add the `macos-private-api` feature.

**Comment by jbolda** [comment]
Builds on all OS should work as of a0e137c802374b6bbf7aa892d595643f1de97dc3.
